### PR TITLE
Add content type as parameter to mock tests

### PR DESCRIPTION
**Pull request by winniehell**
Does what the title says as preparation for XML support (#23).

I'm unsure whether other tests should iterate over supported content types as well. What do you think?

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
This looks good at first glance.  Not sure why the Travis CI build is failing.  I should have time to take a look at it next week.   In the meantime, I think you're on the right track, so keep up the good work.  And thank you for contributing!

**Comment by BigstickCarpet** [comment]
Oh wait... I see that you answered the "failing test" issue in #25.  Way to be on top of things!

**Comment by winniehell** [comment]
Thank you for merging this so quickly! :+1: I'll try to continue working on this.

**Comment by winniehell** [comment]
In the long run, I think, it would be good to have a helper method for passing (and checking) the content type&mdash;maybe as a [supertest/superagent plugin][superagent-plugins]. That should not be too hard to implement but would remove the duplicated code.

[superagent-plugins]: https://github.com/visionmedia/superagent#plugins

**Pull request merged**
