### PR TITLE
Swagger middleware does not support multiple swagger files

### PR DESCRIPTION
**Pull request by grouchal**
we have been trying to get swagger-express-middleware working with multiple swagger files. There are a couple of minor changes required for this to work properly though as 404 responses and empty responses are breaking the express chaining.

Please can you review these minor changes.

### CODE REVIEW

**Comment by grouchal** [comment]
This is a solution for #29

**Comment by grouchal** [comment]
@winniehell sorry I don't understand your comment? You have made a reference to this pull request, but then talk about using another branch.

**Comment by winniehell** [comment]
@grouchal: This pull request is based on [your master branch](https://github.com/grouchal/swagger-express-middleware/tree/master) where you deleted the content of the README file (in the [commit I commented on](https://github.com/grouchal/swagger-express-middleware/commit/e737b2833fc4cfd6969a78de5402b9e87b9eec5a)).

But I think you only want this pull request to contain [aa88673495b440ea16b738438e2c60bece70044e](https://github.com/grouchal/swagger-express-middleware/commit/aa88673495b440ea16b738438e2c60bece70044e) and [e49490940c72645d850cf21a276065df2b128eb9](https://github.com/grouchal/swagger-express-middleware/commit/e49490940c72645d850cf21a276065df2b128eb9).

**Comment by grouchal** [comment]
@winniehell OK I have created a new pull request with the correct files #40

**Pull request closed without merging**
